# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${task_name}/runs/${oc.env:MY_UNIQUE_ID}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${oc.env:MY_UNIQUE_ID}
  subdir: ${hydra.job.num}